project:
  type: website
  output-dir: docs  # Set output directory to docs for GitHub Pages compatibility

website:
  title: "mosesrivera.info"
  site-url: https://mosesrivera100.github.io/mosesrivera.info/
  description: "Moses Rivera's blog"
  #navbar:
    #left:
      #- href: index.qmd
      #  text: Home
      #- about.qmd
  sidebar:
    style: "floating"  # Options: "floating" (scrolls with the page) or "regular" (fixed)
    search: true
    contents:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd.
      - blog/blog.qmd
  reader-mode: true
  back-to-top-navigation: true
  page-footer: 
    #left: 
    center: "Copyright 2024, Moses Rivera" 
    #right:
    #background:
    #foreground:
    #border:



format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



