project:
  type: website

website:
  title: "mosesrivera.info"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

output-dir: docs  # Set output directory to docs for GitHub Pages compatibility

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



